// packages/svelte/src/visual/detail/DetailPanel.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { DetailPanelProps } from './types';

	type Props = DetailPanelProps & { children?: Snippet };

	let {
		className,
		title,
		emptyMessage,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-detail', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-detail">
	<header class="rd-detail__header"><span>{title ?? 'Details'}</span></header>
	{#if children}
		<div class="rd-detail__body">{@render children()}</div>
	{:else}
		<p class="rd-detail__empty">{emptyMessage ?? 'Select a row to view details'}</p>
	{/if}
</section>

// packages/angular/src/visual/detail/detail-panel.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface DetailPanelProps {
  title?: string;
  emptyMessage?: string;
  className?: string;
}

/** @rosettadash/angular/visual/detail — visual.detail */
@Component({
  selector: 'rd-detail',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-detail'" [ngClass]="rootClass()">
      <header class="rd-detail__header"><span>{{ title() ?? 'Details' }}</span></header>
      <p class="rd-detail__empty">{{ emptyMessage() ?? 'Select a row to view details' }}</p>
      <div class="rd-detail__body">
        <ng-content />
      </div>
    </section>
  `,
})
export class DetailPanel {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly emptyMessage = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-detail', this.className()].filter(Boolean).join(' '),
  );
}
