// apps/proof-vue/src/screens/GlobeScreen.vue
<script lang="ts">
export const GLOBE_SOURCE = `<GlobeScreen part="explorer" locale={locale} selectedId={selectedId}>
  <GeoExplorerLayout items={…} selectedId={selectedId} />
  <ThreeGeoGlobe textureUrl markers selectedId />
</GlobeScreen>`;
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { ThreeGeoGlobe } from '@rosettadash/vue/visual/display/3d-geo-globe';
import {
  DEFAULT_WORLD_EQUIRECT_ATTRIBUTION,
  DEFAULT_WORLD_EQUIRECT_URL,
  GLOBE_TEXTURE_SOURCE_OPTIONS,
  MOCK_DESTINATIONS,
} from '@destination-atlas';
import GeoExplorerLayout, { type GeoExplorerListPlacement } from '../components/GeoExplorerLayout.vue';
import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';

const props = withDefaults(
  defineProps<{
    locale: string;
    selectedId: string;
    embedded?: boolean;
    part?: 'explorer' | 'footer';
    listPlacement?: GeoExplorerListPlacement;
  }>(),
  { embedded: false, listPlacement: 'right' },
);

const emit = defineEmits<{
  'update:selectedId': [string];
  focusDestinationOnMap: [string];
}>();

const markers = computed(() =>
  MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    lat: dest.lat,
    lng: dest.lng,
    label: localizedDestinationName(dest, props.locale),
  })),
);

const listItems = computed(() =>
  MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    label: localizedDestinationName(dest, props.locale),
    meta: formatRegionLabel(dest.region),
  })),
);

function selectFromList(id: string) {
  emit('update:selectedId', id);
}

function selectFromGlobe(id: string) {
  if (id === props.selectedId) {
    emit('focusDestinationOnMap', id);
    return;
  }
  emit('update:selectedId', id);
}
</script>

<template>
  <GeoExplorerLayout
    v-if="!embedded || part === 'explorer'"
    :list-placement="listPlacement"
    :items="listItems"
    :selected-id="selectedId"
    @select="selectFromList"
  >
    <div class="da-globe-stage">
      <ThreeGeoGlobe
        class="da-globe-stage__globe"
        title="Destination globe (Three.js)"
        :texture-url="DEFAULT_WORLD_EQUIRECT_URL"
        :markers="markers"
        :selected-id="selectedId"
        @marker-select="selectFromGlobe($event.id)"
      />
    </div>
  </GeoExplorerLayout>

  <div v-if="embedded && part === 'footer'" class="da-maps-footer">
    <p class="da-note">{{ DEFAULT_WORLD_EQUIRECT_ATTRIBUTION }}</p>
    <details class="da-globe-sources">
      <summary>Future globe texture sources</summary>
      <ul>
        <li v-for="source in GLOBE_TEXTURE_SOURCE_OPTIONS" :key="source.id">
          <strong>{{ source.label }}</strong> — {{ source.license }}. {{ source.notes }}
          <span v-if="source.apiKeyRequired"> API key required.</span>
        </li>
      </ul>
    </details>
  </div>
</template>

// apps/proof-angular/src/screens/globe-screen.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { ThreeGeoGlobe } from '@rosettadash/angular/visual/display/3d-geo-globe';
import {
  DEFAULT_WORLD_EQUIRECT_ATTRIBUTION,
  DEFAULT_WORLD_EQUIRECT_URL,
  GLOBE_TEXTURE_SOURCE_OPTIONS,
  MOCK_DESTINATIONS,
} from '@destination-atlas';
import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';
import { AtlasStateService } from '../services/atlas-state.service';
import {
  GeoExplorerLayoutComponent,
  type GeoExplorerListPlacement,
} from '../components/geo-explorer-layout.component';

export type GlobeScreenPart = 'explorer' | 'footer';

@Component({
  selector: 'da-globe-screen',
  standalone: true,
  imports: [ThreeGeoGlobe, GeoExplorerLayoutComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (showExplorer()) {
      <da-geo-explorer-layout
        [listPlacement]="listPlacement()"
        [items]="listItems()"
        [selectedId]="atlas.selectedId()"
        (select)="selectFromList($event)"
      >
        <div class="da-globe-stage">
          <rd-display-3d-geo-globe
            title="Destination globe (Three.js)"
            [textureUrl]="textureUrl"
            [markers]="markers()"
            [selectedId]="atlas.selectedId()"
            (markerSelect)="selectFromGlobe($event)"
          />
        </div>
      </da-geo-explorer-layout>
    }

    @if (showFooter()) {
      <div class="da-maps-footer">
        <p class="da-note">{{ attribution }}</p>
        <details class="da-globe-sources">
          <summary>Future globe texture sources</summary>
          <ul>
            @for (source of textureSources; track source.id) {
              <li>
                <strong>{{ source.label }}</strong> — {{ source.license }}. {{ source.notes }}
                @if (source.apiKeyRequired) {
                  API key required.
                }
              </li>
            }
          </ul>
        </details>
      </div>
    }
  `,
})
export class GlobeScreenComponent {
  readonly screenPart = input<GlobeScreenPart>();
  readonly embedded = input(false);
  readonly listPlacement = input<GeoExplorerListPlacement>('right');

  readonly atlas = inject(AtlasStateService);

  readonly textureUrl = DEFAULT_WORLD_EQUIRECT_URL;
  readonly attribution = DEFAULT_WORLD_EQUIRECT_ATTRIBUTION;
  readonly textureSources = GLOBE_TEXTURE_SOURCE_OPTIONS;

  readonly markers = computed(() =>
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      lat: dest.lat,
      lng: dest.lng,
      label: localizedDestinationName(dest, this.atlas.locale()),
    })),
  );

  readonly listItems = computed(() =>
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      label: localizedDestinationName(dest, this.atlas.locale()),
      meta: formatRegionLabel(dest.region),
    })),
  );

  showExplorer(): boolean {
    const part = this.screenPart();
    if (this.embedded()) {
      return part === 'explorer' || part === undefined;
    }
    return true;
  }

  showFooter(): boolean {
    const part = this.screenPart();
    if (this.embedded()) {
      return part === 'footer';
    }
    return true;
  }

  selectFromList(id: string): void {
    this.atlas.setSelectedId(id);
  }

  selectFromGlobe(id: string): void {
    if (!id) {
      return;
    }
    this.atlas.setSelectedId(id);
  }
}
