// apps/proof-react/src/screens/MapScreen.tsx
import { useState } from 'react';
import { GeoExplorerLayout, type GeoExplorerListPlacement } from '@rosettadash/react/layout/geo-explorer';
import { GeoMap } from '@rosettadash/react/visual/display/geo-map';
import { SelectInput } from '@rosettadash/react/visual/input/select';
import { TextInput } from '@rosettadash/react/visual/input/text';
import { GEO_MAP_PROVIDERS, MOCK_DESTINATIONS, getDestinationById, type GeoMapProvider } from '@destination-atlas';
import type { AtlasContext } from '../state/useDestinationAtlasState';
import { useConsumerSecrets } from '../state/consumer-secrets-context';
import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';
import { destinationMapView, resolveMapLocationQuery } from '../lib/map-location';

export const MAP_SOURCE = `<MapScreen part="toolbar|explorer" mapProvider={mapProvider} selectedId={selectedId}>
  <TextInput label="Request location" value={mapLocationQuery} />
  <SelectInput label="Map provider" value={mapProvider} />
  <GeoExplorerLayout listPlacement={listPlacement} items={destinationItems} selectedId={selectedId}>
    <GeoMap center={…} zoom={…} markers={destinationMarkers} selectedId={selectedId} apiKey={byokGoogleMapsKey} />
  </GeoExplorerLayout>
</MapScreen>`;

type MapScreenPart = 'toolbar' | 'explorer';

type Props = Pick<
  AtlasContext,
  | 'locale'
  | 'selectedId'
  | 'setSelectedId'
  | 'mapProvider'
  | 'setMapProvider'
  | 'mapLocationQuery'
  | 'setMapLocationQuery'
  | 'mapViewOverride'
  | 'focusDestinationOnMap'
  | 'goToMapView'
  | 'setScreen'
  | 'setHighlightTarget'
> & {
  embedded?: boolean;
  part?: MapScreenPart;
  listPlacement?: GeoExplorerListPlacement;
};

export function MapScreen({
  locale,
  selectedId,
  setSelectedId,
  mapProvider,
  setMapProvider,
  mapLocationQuery,
  setMapLocationQuery,
  mapViewOverride,
  focusDestinationOnMap,
  goToMapView,
  setScreen,
  setHighlightTarget,
  embedded = false,
  part,
  listPlacement = 'right',
}: Props) {
  const [locationError, setLocationError] = useState('');
  const secrets = useConsumerSecrets();
  const googleMapsApiKey = secrets.googleMapsApiKey;
  const maplibreTileUrl = secrets.maplibreTileUrl;

  const openIntegrationsSettings = () => {
    setHighlightTarget('integrations');
    setScreen('settings');
  };

  const selected = getDestinationById(selectedId);
  const view =
    mapViewOverride ??
    (selected ? destinationMapView(selected, locale) : { lat: 20, lng: 0, zoom: 2, label: 'World' });

  const markers = MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    lat: dest.lat,
    lng: dest.lng,
    label: localizedDestinationName(dest, locale),
  }));

  const listItems = MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    label: localizedDestinationName(dest, locale),
    meta: formatRegionLabel(dest.region),
  }));

  const activeProvider = GEO_MAP_PROVIDERS.find((entry) => entry.id === mapProvider);

  const submitLocation = () => {
    const resolved = resolveMapLocationQuery(mapLocationQuery, locale);
    if (!resolved) {
      setLocationError('No match — try a dataset destination (Tokyo, Paris, New York City…) or lat, lng (40.71, -74.01).');
      return;
    }
    setLocationError('');
    const matchedDest = MOCK_DESTINATIONS.find(
      (dest) => localizedDestinationName(dest, locale).toLowerCase() === resolved.label.toLowerCase(),
    );
    if (matchedDest) {
      focusDestinationOnMap(matchedDest.id);
      return;
    }
    goToMapView(resolved);
  };

  const selectDestination = (id: string) => {
    setSelectedId(id);
  };

  const renderToolbar = () => (
    <>
      <div className="rd-map-location">
        <TextInput
          label="Request location"
          placeholder="Destination name or lat, lng…"
          value={mapLocationQuery}
          onChange={(value) => {
            setMapLocationQuery(value);
            if (locationError) {
              setLocationError('');
            }
          }}
        />
        <button type="button" className="rd-button" onClick={submitLocation}>
          Go to location
        </button>
      </div>
      {locationError ? <p className="da-map-location-error">{locationError}</p> : null}
      {view.label ? (
        <p className="da-note da-maps-toolbar__view-label">
          Map view: <strong>{view.label}</strong>
          {mapViewOverride ? ' (custom coordinates)' : selected ? '' : ' (default)'}
        </p>
      ) : null}

      <SelectInput
        label="Map provider"
        options={GEO_MAP_PROVIDERS.map((entry) => ({
          value: entry.id,
          label: entry.label,
        }))}
        value={mapProvider}
        onChange={(value) => setMapProvider(value as GeoMapProvider)}
      />
      {activeProvider ? (
        <dl className="da-provider-meta">
          <dt>Cost</dt>
          <dd>{activeProvider.costSummary}</dd>
          <dt>API key</dt>
          <dd>{activeProvider.apiKeyRequired ? 'Required' : 'Optional'}</dd>
          <dt>Notes</dt>
          <dd>{activeProvider.notes}</dd>
        </dl>
      ) : null}
      {mapProvider === 'google-maps' && !googleMapsApiKey ? (
        <p className="da-note da-byok-cta">
          Google Maps requires an API key.{' '}
          <button type="button" className="da-locale-link" onClick={openIntegrationsSettings}>
            Configure in Settings → Integrations
          </button>{' '}
          or set <code>VITE_GOOGLE_MAPS_API_KEY</code> in <code>.env.local</code>.
        </p>
      ) : null}
      {mapProvider === 'maplibre' && !maplibreTileUrl ? (
        <p className="da-note">
          Using demo MapLibre tiles. Add a MapTiler key in{' '}
          <button type="button" className="da-locale-link" onClick={openIntegrationsSettings}>
            Settings → Integrations
          </button>{' '}
          for hosted vector tiles.
        </p>
      ) : null}
    </>
  );

  const renderExplorer = () => (
    <GeoExplorerLayout
      listPlacement={listPlacement}
      items={listItems}
      selectedId={selectedId}
      onSelect={selectDestination}
    >
      <div className="da-map-stage">
        <GeoMap
          className="da-map-stage__map"
          provider={mapProvider}
          center={JSON.stringify({ lat: view.lat, lng: view.lng })}
          zoom={view.zoom}
          markers={markers}
          selectedId={selectedId}
          apiKey={mapProvider === 'google-maps' ? googleMapsApiKey : undefined}
          tileUrl={mapProvider === 'maplibre' ? maplibreTileUrl : undefined}
          onMarkerSelect={({ id }) => selectDestination(id)}
        />
      </div>
    </GeoExplorerLayout>
  );

  if (embedded && part === 'toolbar') {
    return <div className="da-maps-toolbar__map-fields">{renderToolbar()}</div>;
  }

  if (embedded && part === 'explorer') {
    return renderExplorer();
  }

  if (embedded) {
    return (
      <>
        {renderToolbar()}
        {renderExplorer()}
      </>
    );
  }

  return (
    <section className="da-panel">
      <h2>Map</h2>
      <p>2D exploration with developer-selectable geo-map provider.</p>
      {renderToolbar()}
      {renderExplorer()}
    </section>
  );
}

// apps/proof-angular/src/screens/map-screen.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input, signal } from '@angular/core';
import { GeoMap } from '@rosettadash/angular/visual/display/geo-map';
import {
  GEO_MAP_PROVIDERS,
  MOCK_DESTINATIONS,
  getDestinationById,
  type GeoMapProvider,
} from '@destination-atlas';
import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';
import { destinationMapView, resolveMapLocationQuery } from '../lib/map-location';
import { AtlasStateService } from '../services/atlas-state.service';
import { ConsumerSecretsService } from '../services/consumer-secrets.service';
import {
  DaBoundSelectInputComponent,
  DaBoundTextInputComponent,
} from '../components/proof-form-fields.component';
import {
  GeoExplorerLayoutComponent,
  type GeoExplorerListPlacement,
} from '../components/geo-explorer-layout.component';

export type MapScreenPart = 'toolbar' | 'explorer';

@Component({
  selector: 'da-map-screen',
  standalone: true,
  imports: [
    GeoMap,
    DaBoundTextInputComponent,
    DaBoundSelectInputComponent,
    GeoExplorerLayoutComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (showToolbar()) {
      <div class="da-maps-toolbar__map-fields">
        <div class="rd-map-location">
          <da-bound-text-input
            [fieldLabel]="'Request location'"
            placeholder="Destination name or lat, lng…"
            [value]="atlas.mapLocationQuery()"
            (valueChange)="onLocationQueryChange($event)"
          />
          <button type="button" class="rd-button" (click)="submitLocation()">Go to location</button>
        </div>
        @if (locationError()) {
          <p class="da-map-location-error">{{ locationError() }}</p>
        }
        @if (view().label) {
          <p class="da-note da-maps-toolbar__view-label">
            Map view: <strong>{{ view().label }}</strong>
            @if (atlas.mapViewOverride()) {
              (custom coordinates)
            }
          </p>
        }

        <da-bound-select-input
          [fieldLabel]="'Map provider'"
          [options]="mapProviderOptions()"
          [value]="atlas.mapProvider()"
          (valueChange)="onMapProviderChange($event)"
        />
        @if (activeProvider(); as provider) {
          <dl class="da-provider-meta">
            <dt>Cost</dt>
            <dd>{{ provider.costSummary }}</dd>
            <dt>API key</dt>
            <dd>{{ provider.apiKeyRequired ? 'Required' : 'Optional' }}</dd>
            <dt>Notes</dt>
            <dd>{{ provider.notes }}</dd>
          </dl>
        }
        @if (atlas.mapProvider() === 'google-maps' && !secrets.googleMapsApiKey()) {
          <p class="da-note da-byok-cta">
            Google Maps requires an API key.
            <button type="button" class="da-locale-link" (click)="openIntegrationsSettings()">
              Configure in Settings → Integrations
            </button>
            or set <code>VITE_GOOGLE_MAPS_API_KEY</code> in <code>.env.local</code>.
          </p>
        }
        @if (atlas.mapProvider() === 'maplibre' && !secrets.maplibreTileUrl()) {
          <p class="da-note">
            Using demo MapLibre tiles. Add a MapTiler key in
            <button type="button" class="da-locale-link" (click)="openIntegrationsSettings()">
              Settings → Integrations
            </button>
            for hosted vector tiles.
          </p>
        }
      </div>
    }

    @if (showExplorer()) {
      <da-geo-explorer-layout
        [listPlacement]="listPlacement()"
        [items]="listItems()"
        [selectedId]="atlas.selectedId()"
        (select)="selectDestination($event)"
      >
        <div class="da-map-stage">
          <rd-geo-map
            class="da-map-stage__map"
            [provider]="atlas.mapProvider()"
            [center]="centerJson()"
            [zoom]="view().zoom"
            [markers]="markers()"
            [selectedId]="atlas.selectedId()"
            [apiKey]="atlas.mapProvider() === 'google-maps' ? secrets.googleMapsApiKey() : undefined"
            [tileUrl]="atlas.mapProvider() === 'maplibre' ? secrets.maplibreTileUrl() : undefined"
            (markerSelect)="selectDestination($event.id)"
          />
        </div>
      </da-geo-explorer-layout>
    }
  `,
})
export class MapScreenComponent {
  readonly screenPart = input<MapScreenPart>();
  readonly embedded = input(false);
  readonly listPlacement = input<GeoExplorerListPlacement>('right');

  readonly atlas = inject(AtlasStateService);
  readonly secrets = inject(ConsumerSecretsService);

  readonly locationError = signal('');

  readonly view = computed(() => {
    const override = this.atlas.mapViewOverride();
    if (override) {
      return override;
    }
    const selected = getDestinationById(this.atlas.selectedId());
    return selected
      ? destinationMapView(selected, this.atlas.locale())
      : { lat: 20, lng: 0, zoom: 2, label: 'World' };
  });

  readonly centerJson = computed(() => JSON.stringify({ lat: this.view().lat, lng: this.view().lng }));

  readonly markers = computed(() =>
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      lat: dest.lat,
      lng: dest.lng,
      label: localizedDestinationName(dest, this.atlas.locale()),
    })),
  );

  readonly listItems = computed(() =>
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      label: localizedDestinationName(dest, this.atlas.locale()),
      meta: formatRegionLabel(dest.region),
    })),
  );

  readonly mapProviderOptions = computed(() =>
    GEO_MAP_PROVIDERS.map((entry) => ({ value: entry.id, label: entry.label })),
  );

  readonly activeProvider = computed(() =>
    GEO_MAP_PROVIDERS.find((entry) => entry.id === this.atlas.mapProvider()),
  );

  showToolbar(): boolean {
    const part = this.screenPart();
    return !this.embedded() ? true : part === 'toolbar' || part === undefined;
  }

  showExplorer(): boolean {
    const part = this.screenPart();
    return !this.embedded() ? true : part === 'explorer' || part === undefined;
  }

  onLocationQueryChange(value: string): void {
    this.atlas.mapLocationQuery.set(value);
    if (this.locationError()) {
      this.locationError.set('');
    }
  }

  submitLocation(): void {
    const resolved = resolveMapLocationQuery(this.atlas.mapLocationQuery(), this.atlas.locale());
    if (!resolved) {
      this.locationError.set(
        'No match — try a dataset destination (Tokyo, Paris, New York City…) or lat, lng (40.71, -74.01).',
      );
      return;
    }
    this.locationError.set('');
    const matchedDest = MOCK_DESTINATIONS.find(
      (dest) =>
        localizedDestinationName(dest, this.atlas.locale()).toLowerCase() === resolved.label.toLowerCase(),
    );
    if (matchedDest) {
      this.atlas.focusDestinationOnMap(matchedDest.id);
      return;
    }
    this.atlas.goToMapView(resolved);
  }

  selectDestination(id: string): void {
    this.atlas.setSelectedId(id);
  }

  openIntegrationsSettings(): void {
    this.atlas.setHighlightTarget('integrations');
    this.atlas.setScreen('settings');
  }

  onMapProviderChange(value: string): void {
    this.atlas.setMapProvider(value as GeoMapProvider);
  }
}
