// packages/svelte/src/visual/news/article-detail/NewsArticleDetail.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { NewsArticleDetailProps } from './types';

	type Props = NewsArticleDetailProps & { children?: Snippet };

	let {
		className,
		title,
		emptyMessage,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-news-article-detail', 'rd-detail', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-news-article-detail">
	<header class="rd-detail__header"><span>{title ?? 'Article'}</span></header>
	{#if children}
		<div class="rd-detail__body">{@render children()}</div>
	{:else}
		<p class="rd-detail__empty">{emptyMessage ?? 'Select a headline in News Results'}</p>
	{/if}
</section>

// packages/angular/src/visual/news/article-detail/news-article-detail.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface NewsArticleDetailProps {
  title?: string;
  emptyMessage?: string;
  className?: string;
}

/** @rosettadash/angular/visual/news/article-detail — visual.news.article-detail */
@Component({
  selector: 'rd-news-article-detail',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-news-article-detail'" [ngClass]="rootClass()">
      <header class="rd-detail__header"><span>{{ title() ?? 'Article' }}</span></header>
      <p class="rd-detail__empty">{{ emptyMessage() ?? 'Select a headline in News Results' }}</p>
      <div class="rd-detail__body">
        <ng-content />
      </div>
    </section>
  `,
})
export class NewsArticleDetail {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly emptyMessage = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-news-article-detail', 'rd-detail', this.className()].filter(Boolean).join(' '),
  );
}
