// apps/proof-vue/src/components/RoleGatePanel.vue
<script setup lang="ts">
import { RoleGate } from '@rosettadash/vue/domain/role-gate';
import { roleLabel, type AtlasUserRole } from '../lib/roles';

const props = withDefaults(
  defineProps<{
    gateLabel?: string;
    currentRole: AtlasUserRole;
    allowedRoles?: string[];
    statusText?: string;
    hiddenStatusText?: string;
  }>(),
  {
    allowedRoles: () => ['admin'],
  },
);
</script>

<template>
  <RoleGate
    :label="gateLabel"
    :current-role="currentRole"
    :allowed-roles="allowedRoles"
    :status-text="statusText"
    :hidden-status-text="hiddenStatusText ?? `This section is hidden for ${roleLabel(props.currentRole)} role.`"
  >
    <slot />
  </RoleGate>
</template>

// apps/proof-svelte/src/components/RoleGatePanel.svelte
<script lang="ts">
  import { roleAllows, roleLabel, type AtlasUserRole } from '../lib/roles';
  import type { Snippet } from 'svelte';

  let {
    gateLabel,
    currentRole,
    allowedRoles = ['admin'],
    statusText,
    hiddenStatusText,
    hideWhenDenied = false,
    children,
  }: {
    gateLabel?: string;
    currentRole: AtlasUserRole;
    allowedRoles?: string[];
    statusText?: string;
    hiddenStatusText?: string;
    hideWhenDenied?: boolean;
    children?: Snippet;
  } = $props();

  const allowed = $derived(roleAllows(currentRole, allowedRoles));
</script>

{#if allowed}
  <section class="rd-role-gate">
    {#if gateLabel}<span class="rd-field__label">{gateLabel}</span>{/if}
    {#if statusText}<p class="rd-role-gate__status">{statusText}</p>{/if}
    {@render children?.()}
  </section>
{:else if !hideWhenDenied}
  <p class="rd-role-gate__status rd-role-gate__status--hidden">{hiddenStatusText ?? `This section is hidden for ${roleLabel(currentRole)} role.`}</p>
{/if}
