// apps/proof-angular/src/components/role-gate-panel.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { roleAllows, roleLabel, type AtlasUserRole } from '../lib/roles';

@Component({
  selector: 'da-role-gate-panel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (allowed()) {
      <section class="rd-role-gate">
        @if (gateLabel()) {
          <span class="rd-field__label">{{ gateLabel() }}</span>
        }
        @if (statusText()) {
          <p class="rd-role-gate__status">{{ statusText() }}</p>
        }
        <ng-content />
      </section>
    } @else if (!hideWhenDenied()) {
      <p class="rd-role-gate__status rd-role-gate__status--hidden">{{ hiddenMessage() }}</p>
    }
  `,
})
export class RoleGatePanelComponent {
  readonly gateLabel = input<string>();
  readonly currentRole = input.required<AtlasUserRole>();
  readonly allowedRoles = input<string[]>(['admin']);
  readonly statusText = input<string>();
  readonly hiddenStatusText = input<string>();
  readonly hideWhenDenied = input(false);

  readonly allowed = computed(() => roleAllows(this.currentRole(), this.allowedRoles()));

  readonly hiddenMessage = computed(() => {
    if (this.hiddenStatusText()) {
      return this.hiddenStatusText();
    }
    return `This section is hidden for ${roleLabel(this.currentRole())} role.`;
  });
}

// apps/proof-svelte/src/components/RoleGatePanel.svelte
<script lang="ts">
  import { roleAllows, roleLabel, type AtlasUserRole } from '../lib/roles';
  import type { Snippet } from 'svelte';

  let {
    gateLabel,
    currentRole,
    allowedRoles = ['admin'],
    statusText,
    hiddenStatusText,
    hideWhenDenied = false,
    children,
  }: {
    gateLabel?: string;
    currentRole: AtlasUserRole;
    allowedRoles?: string[];
    statusText?: string;
    hiddenStatusText?: string;
    hideWhenDenied?: boolean;
    children?: Snippet;
  } = $props();

  const allowed = $derived(roleAllows(currentRole, allowedRoles));
</script>

{#if allowed}
  <section class="rd-role-gate">
    {#if gateLabel}<span class="rd-field__label">{gateLabel}</span>{/if}
    {#if statusText}<p class="rd-role-gate__status">{statusText}</p>{/if}
    {@render children?.()}
  </section>
{:else if !hideWhenDenied}
  <p class="rd-role-gate__status rd-role-gate__status--hidden">{hiddenStatusText ?? `This section is hidden for ${roleLabel(currentRole)} role.`}</p>
{/if}
