// apps/proof-svelte/src/components/BoundSelectInput.svelte
<script lang="ts">
  let {
    fieldLabel,
    placeholder,
    value = '',
    options = [],
    onValueChange,
  }: {
    fieldLabel?: string;
    placeholder?: string;
    value?: string;
    options?: Array<{ value: string; label: string }>;
    onValueChange?: (value: string) => void;
  } = $props();
</script>

<section class="rd-input-select">
  {#if fieldLabel}<span class="rd-field__label">{fieldLabel}</span>{/if}
  <select
    class="rd-select"
    onchange={(event) => onValueChange?.((event.currentTarget as HTMLSelectElement).value)}
  >
    {#if placeholder}<option value="" selected={!(value ?? '')}>{placeholder}</option>{/if}
    {#each options as option (option.value)}
      <option value={option.value} selected={option.value === (value ?? '')}>{option.label}</option>
    {/each}
  </select>
</section>

// apps/proof-vue/src/components/BoundSelectInput.vue
<script setup lang="ts">
defineProps<{
  fieldLabel?: string;
  placeholder?: string;
  value?: string;
  options?: Array<{ value: string; label: string }>;
}>();

const emit = defineEmits<{ 'update:value': [string] }>();
</script>

<template>
  <section class="rd-input-select">
    <span v-if="fieldLabel" class="rd-field__label">{{ fieldLabel }}</span>
    <select
      class="rd-select"
      :value="value ?? ''"
      @change="emit('update:value', ($event.target as HTMLSelectElement).value)"
    >
      <option v-if="placeholder" value="" :selected="!(value ?? '')">{{ placeholder }}</option>
      <option
        v-for="option in options ?? []"
        :key="option.value"
        :value="option.value"
        :selected="option.value === (value ?? '')"
      >
        {{ option.label }}
      </option>
    </select>
  </section>
</template>
