// packages/react/src/visual/display/3d-geo-globe/ThreeGeoGlobe.tsx
import { forwardRef, useEffect, useRef, type CSSProperties, type ReactNode } from 'react';
import {
  cameraPositionFacingLatLng,
  GLOBE_CAMERA_DISTANCE,
  GLOBE_FLY_DURATION_MS,
  GLOBE_HEIGHT_SEGMENTS,
  GLOBE_RADIUS,
  GLOBE_WIDTH_SEGMENTS,
  latLngToGlobePosition,
  patchEquirectGlobeMaterial,
  prepareEquirectGlobeTexture,
  isGlobePointerClick,
  resolveGlobePickId,
} from '@rosettadash/web-components/visual/display/3d-geo-globe';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

export interface GlobeMarker {
  id: string;
  lat: number;
  lng: number;
  label?: string;
}

export interface ThreeGeoGlobeProps {
  title?: string;
  textureUrl?: string;
  markers?: GlobeMarker[];
  selectedId?: string;
  onMarkerSelect?: (id: string) => void;
  minHeight?: string | number;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

function toVector3(point: { x: number; y: number; z: number }): THREE.Vector3 {
  return new THREE.Vector3(point.x, point.y, point.z);
}

/** @rosettadash/react/visual/display/3d-geo-globe — Three.js globe with destination markers */
export const ThreeGeoGlobe = forwardRef<HTMLElement, ThreeGeoGlobeProps>(function ThreeGeoGlobe(
  {
    title,
    textureUrl,
    markers = [],
    selectedId,
    onMarkerSelect,
    minHeight = '28rem',
    className,
    style,
    children,
  },
  ref,
) {
  const hostRef = useRef<HTMLDivElement>(null);
  const markerMeshesRef = useRef<Map<string, THREE.Mesh>>(new Map());
  const syncMarkersRef = useRef<(() => void) | null>(null);
  const flyToLatLngRef = useRef<((lat: number, lng: number, immediate?: boolean) => void) | null>(
    null,
  );
  const hasFacedSelectionRef = useRef(false);
  const propsRef = useRef({ markers, selectedId, onMarkerSelect });
  propsRef.current = { markers, selectedId, onMarkerSelect };

  const rootClass = ['rd-display-3d-geo-globe', className].filter(Boolean).join(' ');
  const hostStyle: CSSProperties = {
    ...style,
    minHeight: typeof minHeight === 'number' ? `${minHeight}px` : minHeight,
  };

  useEffect(() => {
    const host = hostRef.current;
    if (!host) {
      return;
    }

    const scene = new THREE.Scene();
    scene.background = new THREE.Color('#0b1220');

    const camera = new THREE.PerspectiveCamera(45, 1, 0.1, 100);
    camera.position.set(0, 0.4, GLOBE_CAMERA_DISTANCE);

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.domElement.style.display = 'block';
    renderer.domElement.style.width = '100%';
    renderer.domElement.style.height = '100%';
    host.appendChild(renderer.domElement);

    scene.add(new THREE.AmbientLight(0xffffff, 0.72));
    const keyLight = new THREE.DirectionalLight(0xffffff, 1.05);
    keyLight.position.set(4, 6, 5);
    scene.add(keyLight);

    const globeMaterial = new THREE.MeshStandardMaterial({ color: '#1d4ed8' });
    patchEquirectGlobeMaterial(globeMaterial);
    const globe = new THREE.Mesh(
      new THREE.SphereGeometry(GLOBE_RADIUS, GLOBE_WIDTH_SEGMENTS, GLOBE_HEIGHT_SEGMENTS),
      globeMaterial,
    );
    scene.add(globe);

    let textureLoadId = 0;
    if (textureUrl) {
      const loadId = ++textureLoadId;
      new THREE.TextureLoader().load(textureUrl, (texture) => {
        if (loadId !== textureLoadId) {
          texture.dispose();
          return;
        }
        prepareEquirectGlobeTexture(texture, {
          colorSpace: THREE.SRGBColorSpace,
          wrapS: THREE.RepeatWrapping,
          wrapT: THREE.ClampToEdgeWrapping,
          minFilter: THREE.LinearFilter,
          magFilter: THREE.LinearFilter,
          anisotropy: Math.min(16, renderer.capabilities.getMaxAnisotropy()),
        });
        globeMaterial.map = texture;
        globeMaterial.color.set('#ffffff');
        globeMaterial.needsUpdate = true;
      });
    }

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.08;
    controls.minDistance = 2.8;
    controls.maxDistance = 8;
    controls.autoRotate = true;
    controls.autoRotateSpeed = 0.6;

    const markerGeometry = new THREE.SphereGeometry(0.06, 12, 12);
    const raycaster = new THREE.Raycaster();
    const pointer = new THREE.Vector2();
    let pointerDown: { x: number; y: number } | null = null;

    const syncMarkers = () => {
      const { markers: nextMarkers, selectedId: nextSelected } = propsRef.current;
      const meshes = markerMeshesRef.current;

      for (const id of [...meshes.keys()]) {
        if (!nextMarkers.some((marker) => marker.id === id)) {
          const mesh = meshes.get(id);
          if (mesh) {
            (mesh.material as THREE.Material).dispose();
            mesh.removeFromParent();
          }
          meshes.delete(id);
        }
      }

      for (const marker of nextMarkers) {
        let mesh = meshes.get(marker.id);
        if (!mesh) {
          mesh = new THREE.Mesh(markerGeometry, new THREE.MeshStandardMaterial({ color: '#f87171' }));
          mesh.userData['id'] = marker.id;
          scene.add(mesh);
          meshes.set(marker.id, mesh);
        }
        mesh.position.copy(toVector3(latLngToGlobePosition(marker.lat, marker.lng, GLOBE_RADIUS)));
        const material = mesh.material as THREE.MeshStandardMaterial;
        const selected = marker.id === nextSelected;
        material.color.set(selected ? '#fbbf24' : '#f87171');
        material.emissive.set(selected ? '#92400e' : '#000000');
        material.emissiveIntensity = selected ? 0.35 : 0;
      }
    };

    syncMarkers();
    syncMarkersRef.current = syncMarkers;

    let flyFrameId = 0;
    flyToLatLngRef.current = (lat: number, lng: number, immediate = false) => {
      cancelAnimationFrame(flyFrameId);
      const distance = camera.position.length() || GLOBE_CAMERA_DISTANCE;
      const endPos = toVector3(cameraPositionFacingLatLng(lat, lng, distance));
      if (immediate) {
        camera.position.copy(endPos);
        controls.update();
        return;
      }
      controls.autoRotate = false;
      const startPos = camera.position.clone();
      const flyStart = performance.now();

      const animateFly = (now: number) => {
        const t = Math.min((now - flyStart) / GLOBE_FLY_DURATION_MS, 1);
        const eased = 1 - (1 - t) ** 3;
        camera.position.lerpVectors(startPos, endPos, eased);
        controls.update();
        if (t < 1) {
          flyFrameId = requestAnimationFrame(animateFly);
        } else {
          controls.autoRotate = true;
        }
      };

      flyFrameId = requestAnimationFrame(animateFly);
    };

    const resize = () => {
      const width = host.clientWidth || 1;
      const height = host.clientHeight || 1;
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
      renderer.setSize(width, height, false);
    };

    const resizeObserver = new ResizeObserver(resize);
    resizeObserver.observe(host);
    resize();

    let animationId = 0;
    const tick = () => {
      controls.update();
      renderer.render(scene, camera);
      animationId = requestAnimationFrame(tick);
    };
    tick();

    const onPointerDown = (event: PointerEvent) => {
      if (event.button !== 0) {
        return;
      }
      pointerDown = { x: event.clientX, y: event.clientY };
    };

    const pickFromPointer = (event: PointerEvent) => {
      const rect = renderer.domElement.getBoundingClientRect();
      pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
      pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(pointer, camera);
      const hits = raycaster.intersectObjects([globe, ...markerMeshesRef.current.values()]);
      const first = hits[0];
      const firstMesh = first?.object as THREE.Mesh | undefined;
      const markerHitId =
        firstMesh && firstMesh !== globe
          ? (firstMesh.userData?.['id'] as string | undefined)
          : undefined;
      const globeHit = firstMesh === globe ? first : undefined;
      const id = resolveGlobePickId(
        propsRef.current.markers,
        markerHitId,
        globeHit ? { x: globeHit.point.x, y: globeHit.point.y, z: globeHit.point.z } : undefined,
      );
      if (id) {
        propsRef.current.onMarkerSelect?.(id);
      }
    };

    const onPointerUp = (event: PointerEvent) => {
      if (event.button !== 0) {
        return;
      }
      const start = pointerDown;
      pointerDown = null;
      if (!isGlobePointerClick(start, event.clientX, event.clientY)) {
        return;
      }
      pickFromPointer(event);
    };

    const onPointerCancel = () => {
      pointerDown = null;
    };

    renderer.domElement.addEventListener('pointerdown', onPointerDown);
    renderer.domElement.addEventListener('pointerup', onPointerUp);
    renderer.domElement.addEventListener('pointercancel', onPointerCancel);

    return () => {
      syncMarkersRef.current = null;
      flyToLatLngRef.current = null;
      hasFacedSelectionRef.current = false;
      cancelAnimationFrame(flyFrameId);
      renderer.domElement.removeEventListener('pointerdown', onPointerDown);
      renderer.domElement.removeEventListener('pointerup', onPointerUp);
      renderer.domElement.removeEventListener('pointercancel', onPointerCancel);
      cancelAnimationFrame(animationId);
      resizeObserver.disconnect();
      controls.dispose();
      markerMeshesRef.current.forEach((mesh) => {
        (mesh.material as THREE.Material).dispose();
        mesh.removeFromParent();
      });
      markerMeshesRef.current.clear();
      globeGeometryDispose(globe);
      markerGeometry.dispose();
      renderer.dispose();
      renderer.domElement.remove();
      textureLoadId += 1;
    };
  }, [textureUrl]);

  useEffect(() => {
    syncMarkersRef.current?.();
  }, [markers, selectedId]);

  const selectedMarker = markers.find((entry) => entry.id === selectedId);

  useEffect(() => {
    if (!selectedMarker) {
      return;
    }
    const immediate = !hasFacedSelectionRef.current;
    hasFacedSelectionRef.current = true;
    flyToLatLngRef.current?.(selectedMarker.lat, selectedMarker.lng, immediate);
  }, [selectedId, selectedMarker?.lat, selectedMarker?.lng]);

  return (
    <section
      ref={ref as React.RefObject<HTMLElement>}
      className={rootClass}
      style={hostStyle}
      data-testid="rd-display-3d-geo-globe"
      aria-label={title ?? '3D destination globe'}
    >
      {title ? <header className="rd-display-3d-geo-globe__header">{title}</header> : null}
      <div ref={hostRef} className="rd-display-3d-geo-globe__canvas-host" />
      {children}
    </section>
  );
});

function globeGeometryDispose(globe: THREE.Mesh): void {
  globe.geometry.dispose();
  const material = globe.material;
  if (Array.isArray(material)) {
    material.forEach((entry) => entry.dispose());
  } else {
    material.dispose();
    if (material instanceof THREE.MeshStandardMaterial && material.map) {
      material.map.dispose();
    }
  }
}

// packages/angular/src/visual/display/3d-geo-globe/three-geo-globe.ts
import { NgClass } from '@angular/common';
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  OnDestroy,
  computed,
  effect,
  input,
  output,
  viewChild,
} from '@angular/core';
import {
  cameraPositionFacingLatLng,
  GLOBE_CAMERA_DISTANCE,
  GLOBE_FLY_DURATION_MS,
  GLOBE_HEIGHT_SEGMENTS,
  GLOBE_RADIUS,
  GLOBE_WIDTH_SEGMENTS,
  latLngToGlobePosition,
  patchEquirectGlobeMaterial,
  prepareEquirectGlobeTexture,
  isGlobePointerClick,
  resolveGlobePickId,
} from '@rosettadash/web-components/visual/display/3d-geo-globe';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

export interface GlobeMarker {
  id: string;
  lat: number;
  lng: number;
  label?: string;
}

/** Public props for visual/display/3d-geo-globe. */
export interface ThreeGeoGlobeProps {
  title?: string;
  textureUrl?: string;
  markers?: GlobeMarker[];
  selectedId?: string;
  minHeight?: string | number;
  className?: string;
}

function toVector3(point: { x: number; y: number; z: number }): THREE.Vector3 {
  return new THREE.Vector3(point.x, point.y, point.z);
}

function globeGeometryDispose(globe: THREE.Mesh): void {
  globe.geometry.dispose();
  const material = globe.material;
  if (Array.isArray(material)) {
    material.forEach((entry) => entry.dispose());
  } else {
    material.dispose();
    if (material instanceof THREE.MeshStandardMaterial && material.map) {
      material.map.dispose();
    }
  }
}

/** @rosettadash/angular/visual/display/3d-geo-globe — Three.js globe with destination markers */
@Component({
  selector: 'rd-display-3d-geo-globe',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section
      [attr.data-testid]="'rd-display-3d-geo-globe'"
      [ngClass]="rootClass()"
      [attr.aria-label]="title() ?? '3D destination globe'"
      [style.minHeight]="minHeightStyle()"
    >
      @if (title()) {
        <header class="rd-display-3d-geo-globe__header">{{ title() }}</header>
      }
      <div #canvasHost class="rd-display-3d-geo-globe__canvas-host"></div>
      <ng-content />
    </section>
  `,
})
export class ThreeGeoGlobe implements AfterViewInit, OnDestroy {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly textureUrl = input<string | undefined>(undefined);
  readonly markers = input<GlobeMarker[]>([]);
  readonly selectedId = input<string | undefined>(undefined);
  readonly minHeight = input<string | number>('28rem');

  readonly markerSelect = output<string>();

  private readonly canvasHost = viewChild<ElementRef<HTMLDivElement>>('canvasHost');

  readonly rootClass = computed(() =>
    ['rd-display-3d-geo-globe', this.className()].filter(Boolean).join(' '),
  );

  readonly minHeightStyle = computed(() => {
    const value = this.minHeight();
    return typeof value === 'number' ? `${value}px` : value;
  });

  private markerMeshes = new Map<string, THREE.Mesh>();
  private syncMarkers: (() => void) | null = null;
  private flyToLatLng: ((lat: number, lng: number, immediate?: boolean) => void) | null = null;
  private disposeRuntime: (() => void) | null = null;
  private mounted = false;
  private hasFacedSelection = false;

  constructor() {
    effect(() => {
      this.markers();
      this.selectedId();
      if (this.mounted) {
        this.syncMarkers?.();
      }
    });

    effect(() => {
      const selectedId = this.selectedId();
      this.markers();
      if (!this.mounted || !selectedId) {
        return;
      }
      this.faceSelection(!this.hasFacedSelection);
    });
  }

  ngAfterViewInit(): void {
    this.mountScene();
    this.mounted = true;
    this.syncMarkers?.();
    this.faceSelection(true);
  }

  ngOnDestroy(): void {
    this.disposeRuntime?.();
    this.mounted = false;
    this.hasFacedSelection = false;
  }

  private faceSelection(immediate: boolean): void {
    const selectedId = this.selectedId();
    if (!selectedId) {
      return;
    }
    const marker = this.markers().find((entry) => entry.id === selectedId);
    if (!marker) {
      return;
    }
    this.flyToLatLng?.(marker.lat, marker.lng, immediate);
    this.hasFacedSelection = true;
  }

  private mountScene(): void {
    const host = this.canvasHost()?.nativeElement;
    if (!host) {
      return;
    }

    const scene = new THREE.Scene();
    scene.background = new THREE.Color('#0b1220');

    const camera = new THREE.PerspectiveCamera(45, 1, 0.1, 100);
    camera.position.set(0, 0.4, GLOBE_CAMERA_DISTANCE);

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.domElement.style.display = 'block';
    renderer.domElement.style.width = '100%';
    renderer.domElement.style.height = '100%';
    host.appendChild(renderer.domElement);

    scene.add(new THREE.AmbientLight(0xffffff, 0.72));
    const keyLight = new THREE.DirectionalLight(0xffffff, 1.05);
    keyLight.position.set(4, 6, 5);
    scene.add(keyLight);

    const globeMaterial = new THREE.MeshStandardMaterial({ color: '#1d4ed8' });
    patchEquirectGlobeMaterial(globeMaterial);
    const globe = new THREE.Mesh(
      new THREE.SphereGeometry(GLOBE_RADIUS, GLOBE_WIDTH_SEGMENTS, GLOBE_HEIGHT_SEGMENTS),
      globeMaterial,
    );
    scene.add(globe);

    let textureLoadId = 0;
    const textureUrl = this.textureUrl();
    if (textureUrl) {
      const loadId = ++textureLoadId;
      new THREE.TextureLoader().load(textureUrl, (texture) => {
        if (loadId !== textureLoadId) {
          texture.dispose();
          return;
        }
        prepareEquirectGlobeTexture(texture, {
          colorSpace: THREE.SRGBColorSpace,
          wrapS: THREE.RepeatWrapping,
          wrapT: THREE.ClampToEdgeWrapping,
          minFilter: THREE.LinearFilter,
          magFilter: THREE.LinearFilter,
          anisotropy: Math.min(16, renderer.capabilities.getMaxAnisotropy()),
        });
        globeMaterial.map = texture;
        globeMaterial.color.set('#ffffff');
        globeMaterial.needsUpdate = true;
      });
    }

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.08;
    controls.minDistance = 2.8;
    controls.maxDistance = 8;
    controls.autoRotate = true;
    controls.autoRotateSpeed = 0.6;

    const markerGeometry = new THREE.SphereGeometry(0.06, 12, 12);
    const raycaster = new THREE.Raycaster();
    const pointer = new THREE.Vector2();
    let pointerDown: { x: number; y: number } | null = null;

    const syncMarkers = () => {
      const nextMarkers = this.markers();
      const nextSelected = this.selectedId();
      const meshes = this.markerMeshes;

      for (const id of [...meshes.keys()]) {
        if (!nextMarkers.some((marker) => marker.id === id)) {
          const mesh = meshes.get(id);
          if (mesh) {
            (mesh.material as THREE.Material).dispose();
            mesh.removeFromParent();
          }
          meshes.delete(id);
        }
      }

      for (const marker of nextMarkers) {
        let mesh = meshes.get(marker.id);
        if (!mesh) {
          mesh = new THREE.Mesh(markerGeometry, new THREE.MeshStandardMaterial({ color: '#f87171' }));
          mesh.userData['id'] = marker.id;
          scene.add(mesh);
          meshes.set(marker.id, mesh);
        }
        mesh.position.copy(toVector3(latLngToGlobePosition(marker.lat, marker.lng, GLOBE_RADIUS)));
        const material = mesh.material as THREE.MeshStandardMaterial;
        const selected = marker.id === nextSelected;
        material.color.set(selected ? '#fbbf24' : '#f87171');
        material.emissive.set(selected ? '#92400e' : '#000000');
        material.emissiveIntensity = selected ? 0.35 : 0;
      }
    };

    this.syncMarkers = syncMarkers;

    let flyFrameId = 0;
    this.flyToLatLng = (lat: number, lng: number, immediate = false) => {
      cancelAnimationFrame(flyFrameId);
      const distance = camera.position.length() || GLOBE_CAMERA_DISTANCE;
      const endPos = toVector3(cameraPositionFacingLatLng(lat, lng, distance));
      if (immediate) {
        camera.position.copy(endPos);
        controls.update();
        return;
      }
      controls.autoRotate = false;
      const startPos = camera.position.clone();
      const flyStart = performance.now();

      const animateFly = (now: number) => {
        const t = Math.min((now - flyStart) / GLOBE_FLY_DURATION_MS, 1);
        const eased = 1 - (1 - t) ** 3;
        camera.position.lerpVectors(startPos, endPos, eased);
        controls.update();
        if (t < 1) {
          flyFrameId = requestAnimationFrame(animateFly);
        } else {
          controls.autoRotate = true;
        }
      };

      flyFrameId = requestAnimationFrame(animateFly);
    };

    const resize = () => {
      const width = host.clientWidth || 1;
      const height = host.clientHeight || 1;
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
      renderer.setSize(width, height, false);
    };

    const resizeObserver = new ResizeObserver(resize);
    resizeObserver.observe(host);
    resize();

    let animationId = 0;
    const tick = () => {
      controls.update();
      renderer.render(scene, camera);
      animationId = requestAnimationFrame(tick);
    };
    tick();

    const onPointerDown = (event: PointerEvent) => {
      if (event.button !== 0) {
        return;
      }
      pointerDown = { x: event.clientX, y: event.clientY };
    };

    const pickFromPointer = (event: PointerEvent) => {
      const rect = renderer.domElement.getBoundingClientRect();
      pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
      pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(pointer, camera);
      const hits = raycaster.intersectObjects([globe, ...this.markerMeshes.values()]);
      const first = hits[0];
      const firstMesh = first?.object as THREE.Mesh | undefined;
      const markerHitId =
        firstMesh && firstMesh !== globe
          ? (firstMesh.userData?.['id'] as string | undefined)
          : undefined;
      const globeHit = firstMesh === globe ? first : undefined;
      const id = resolveGlobePickId(
        this.markers(),
        markerHitId,
        globeHit ? { x: globeHit.point.x, y: globeHit.point.y, z: globeHit.point.z } : undefined,
      );
      if (id) {
        this.markerSelect.emit(id);
      }
    };

    const onPointerUp = (event: PointerEvent) => {
      if (event.button !== 0) {
        return;
      }
      const start = pointerDown;
      pointerDown = null;
      if (!isGlobePointerClick(start, event.clientX, event.clientY)) {
        return;
      }
      pickFromPointer(event);
    };

    const onPointerCancel = () => {
      pointerDown = null;
    };

    renderer.domElement.addEventListener('pointerdown', onPointerDown);
    renderer.domElement.addEventListener('pointerup', onPointerUp);
    renderer.domElement.addEventListener('pointercancel', onPointerCancel);

    this.disposeRuntime = () => {
      this.syncMarkers = null;
      this.flyToLatLng = null;
      this.hasFacedSelection = false;
      cancelAnimationFrame(flyFrameId);
      renderer.domElement.removeEventListener('pointerdown', onPointerDown);
      renderer.domElement.removeEventListener('pointerup', onPointerUp);
      renderer.domElement.removeEventListener('pointercancel', onPointerCancel);
      cancelAnimationFrame(animationId);
      resizeObserver.disconnect();
      controls.dispose();
      this.markerMeshes.forEach((mesh) => {
        (mesh.material as THREE.Material).dispose();
        mesh.removeFromParent();
      });
      this.markerMeshes.clear();
      globeGeometryDispose(globe);
      markerGeometry.dispose();
      renderer.dispose();
      renderer.domElement.remove();
      textureLoadId += 1;
    };
  }
}
