// packages/svelte/src/visual/media/flat-video-viewport/FlatVideoViewport.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { FlatCropRect } from '@rosettadash/core';
	import {
		DB_FLAT_VIDEO_VIEWPORT_TAG,
		registerRdFlatVideoViewport,
	} from '@rosettadash/web-components/visual/media/flat-video-viewport';
	import {
		attachHostEvents,
		setHostAttribute,
		setHostProperty,
	} from '../../../lib/custom-element-host';
	import type { FlatVideoViewportProps } from './types';

	let {
		videoSrc,
		sourceWidth,
		sourceHeight,
		cropX,
		cropY,
		cropWidth,
		cropHeight,
		outputWidth,
		outputHeight,
		lockAspectRatio,
		className,
		outputPreviewHost = null,
		onCropChange,
	}: FlatVideoViewportProps = $props();

	let host: HTMLElement;
	let detachEvents = () => {};

	export function play(): Promise<void> {
		return (host as { play?: () => Promise<void> }).play?.() ?? Promise.resolve();
	}
	export function pause(): void {
		(host as { pause?: () => void }).pause?.();
	}
	export function stop(): void {
		(host as { stop?: () => void }).stop?.();
	}
	export function seek(time: number): void {
		(host as { seek?: (t: number) => void }).seek?.(time);
	}
	export function getCurrentTime(): number {
		return (host as { getCurrentTime?: () => number }).getCurrentTime?.() ?? 0;
	}
	export function getDuration(): number {
		return (host as { getDuration?: () => number }).getDuration?.() ?? 0;
	}
	export function isPaused(): boolean {
		return (host as { isPaused?: () => boolean }).isPaused?.() ?? true;
	}
	export function getOutputCanvas(): HTMLCanvasElement | null {
		return (host as { getOutputCanvas?: () => HTMLCanvasElement | null }).getOutputCanvas?.() ?? null;
	}
	export function startRecording(): boolean {
		return (host as { startRecording?: () => boolean }).startRecording?.() ?? false;
	}
	export function stopRecording(): Promise<Blob | null> {
		return (
			(host as { stopRecording?: () => Promise<Blob | null> }).stopRecording?.() ??
			Promise.resolve(null)
		);
	}

	onMount(() => {
		registerRdFlatVideoViewport();
		detachEvents = attachHostEvents(host, {
			'crop-change': (detail) => onCropChange?.(detail as FlatCropRect),
		});
		return () => detachEvents();
	});

	$effect(() => {
		if (!host) {
			return;
		}
		setHostAttribute(host, 'source-width', sourceWidth);
		setHostAttribute(host, 'source-height', sourceHeight);
		setHostAttribute(host, 'crop-x', cropX);
		setHostAttribute(host, 'crop-y', cropY);
		setHostAttribute(host, 'crop-width', cropWidth);
		setHostAttribute(host, 'crop-height', cropHeight);
		setHostAttribute(host, 'output-width', outputWidth);
		setHostAttribute(host, 'output-height', outputHeight);
		setHostAttribute(host, 'lock-aspect-ratio', lockAspectRatio);
		setHostProperty(host, 'videoSrc', videoSrc ?? null);
		setHostProperty(host, 'outputPreviewHost', outputPreviewHost);
	});
</script>

<svelte:element this={DB_FLAT_VIDEO_VIEWPORT_TAG} bind:this={host} class={className} />

// packages/react/src/visual/media/flat-video-viewport/FlatVideoViewport.tsx
import {
  createElement,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  type CSSProperties,
  type RefObject,
} from 'react';
import type { FlatCropRect } from '@rosettadash/core';
import {
  DB_FLAT_VIDEO_VIEWPORT_TAG,
  registerRdFlatVideoViewport,
} from '@rosettadash/web-components/visual/media/flat-video-viewport';
import { useCustomElementHost } from '../../../lib/custom-element-host.js';
import {
  asMediaViewportElement,
  type MediaViewportElement,
} from '../media-viewport-element.js';

export type FlatVideoCropChange = FlatCropRect;

export interface FlatVideoViewportHandle {
  play: () => Promise<void>;
  pause: () => void;
  stop: () => void;
  seek: (time: number) => void;
  getCurrentTime: () => number;
  getDuration: () => number;
  isPaused: () => boolean;
  getOutputCanvas: () => HTMLCanvasElement | null;
  startRecording: () => boolean;
  stopRecording: () => Promise<Blob | null>;
}

export interface FlatVideoViewportProps {
  videoSrc?: string | null;
  sourceWidth: number;
  sourceHeight: number;
  cropX: number;
  cropY: number;
  cropWidth: number;
  cropHeight: number;
  outputWidth?: number;
  outputHeight?: number;
  lockAspectRatio?: boolean;
  className?: string;
  style?: CSSProperties;
  outputPreviewHostRef?: RefObject<HTMLElement | null>;
  outputPreviewHost?: HTMLElement | null;
  onCropChange?: (detail: FlatVideoCropChange) => void;
}

function bindViewportHandle(el: MediaViewportElement | null): FlatVideoViewportHandle {
  return {
    play: () => el?.play() ?? Promise.resolve(),
    pause: () => el?.pause(),
    stop: () => el?.stop(),
    seek: (time) => el?.seek(time),
    getCurrentTime: () => el?.getCurrentTime() ?? 0,
    getDuration: () => el?.getDuration() ?? 0,
    isPaused: () => el?.isPaused() ?? true,
    getOutputCanvas: () => el?.getOutputCanvas() ?? null,
    startRecording: () => el?.startRecording() ?? false,
    stopRecording: () => el?.stopRecording() ?? Promise.resolve(null),
  };
}

/** React wrapper around `<rd-flat-video-viewport>` (WC reference implementation). */
export const FlatVideoViewport = forwardRef<FlatVideoViewportHandle, FlatVideoViewportProps>(
  function FlatVideoViewport(
    {
      videoSrc,
      sourceWidth,
      sourceHeight,
      cropX,
      cropY,
      cropWidth,
      cropHeight,
      outputWidth,
      outputHeight,
      lockAspectRatio,
      className,
      style,
      outputPreviewHostRef,
      outputPreviewHost,
      onCropChange,
    },
    ref,
  ) {
    const elementRef = useRef<HTMLElement | null>(null);
    const previewHost = outputPreviewHost ?? outputPreviewHostRef?.current ?? null;

    const hostRef = useCustomElementHost(
      {
        register: registerRdFlatVideoViewport,
        properties: ['videoSrc', 'outputPreviewHost'],
        attrs: {
          sourceWidth: 'source-width',
          sourceHeight: 'source-height',
          cropX: 'crop-x',
          cropY: 'crop-y',
          cropWidth: 'crop-width',
          cropHeight: 'crop-height',
          outputWidth: 'output-width',
          outputHeight: 'output-height',
          lockAspectRatio: 'lock-aspect-ratio',
        },
        events: {
          'crop-change': 'onCropChange',
        },
      },
      {
        sourceWidth,
        sourceHeight,
        cropX,
        cropY,
        cropWidth,
        cropHeight,
        outputWidth,
        outputHeight,
        lockAspectRatio,
      },
      {
        onCropChange: onCropChange as ((detail: unknown) => void) | undefined,
      },
      (node) => {
        elementRef.current = node;
      },
      {
        videoSrc: videoSrc ?? null,
        outputPreviewHost: previewHost,
      },
    );

    useLayoutEffect(() => {
      const el = elementRef.current;
      if (!el) {
        return;
      }
      const setProperty = (el as { setProperty?: (name: string, value: unknown) => void }).setProperty;
      setProperty?.call(el, 'outputPreviewHost', previewHost);
    }, [previewHost]);

    useEffect(() => {
      const el = elementRef.current;
      if (!el) {
        return;
      }
      const setProperty = (el as { setProperty?: (name: string, value: unknown) => void }).setProperty;
      setProperty?.call(el, 'videoSrc', videoSrc ?? null);
    }, [videoSrc]);

    useImperativeHandle(ref, () => bindViewportHandle(asMediaViewportElement(elementRef.current)));

    return createElement(DB_FLAT_VIDEO_VIEWPORT_TAG, {
      ref: hostRef,
      className,
      style,
    });
  },
);
